#[doc = "Register `MR` reader"]
pub type R = crate::R<MR_SPEC>;
#[doc = "Register `MR` writer"]
pub type W = crate::W<MR_SPEC>;
#[doc = "Field `MODE` reader - Inter-IC Sound Controller Mode"]
pub type MODE_R = crate::BitReader<MODESELECT_A>;
#[doc = "Inter-IC Sound Controller Mode\n\nValue on reset: 0"]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MODESELECT_A {
    #[doc = "0: I2SC_CK and I2SC_WS pin inputs used as bit clock and word select/frame synchronization."]
    SLAVE = 0,
    #[doc = "1: Bit clock and word select/frame synchronization generated by I2SC from MCK and output to I2SC_CK and I2SC_WS pins. Peripheral clock or GCLK is output as master clock on I2SC_MCK if I2SC_MR.IMCKMODE is set."]
    MASTER = 1,
}
impl From<MODESELECT_A> for bool {
    #[inline(always)]
    fn from(variant: MODESELECT_A) -> Self {
        variant as u8 != 0
    }
}
impl MODE_R {
    #[doc = "Get enumerated values variant"]
    #[inline(always)]
    pub fn variant(&self) -> MODESELECT_A {
        match self.bits {
            false => MODESELECT_A::SLAVE,
            true => MODESELECT_A::MASTER,
        }
    }
    #[doc = "I2SC_CK and I2SC_WS pin inputs used as bit clock and word select/frame synchronization."]
    #[inline(always)]
    pub fn is_slave(&self) -> bool {
        *self == MODESELECT_A::SLAVE
    }
    #[doc = "Bit clock and word select/frame synchronization generated by I2SC from MCK and output to I2SC_CK and I2SC_WS pins. Peripheral clock or GCLK is output as master clock on I2SC_MCK if I2SC_MR.IMCKMODE is set."]
    #[inline(always)]
    pub fn is_master(&self) -> bool {
        *self == MODESELECT_A::MASTER
    }
}
#[doc = "Field `MODE` writer - Inter-IC Sound Controller Mode"]
pub type MODE_W<'a, REG, const O: u8> = crate::BitWriter<'a, REG, O, MODESELECT_A>;
impl<'a, REG, const O: u8> MODE_W<'a, REG, O>
where
    REG: crate::Writable + crate::RegisterSpec,
{
    #[doc = "I2SC_CK and I2SC_WS pin inputs used as bit clock and word select/frame synchronization."]
    #[inline(always)]
    pub fn slave(self) -> &'a mut crate::W<REG> {
        self.variant(MODESELECT_A::SLAVE)
    }
    #[doc = "Bit clock and word select/frame synchronization generated by I2SC from MCK and output to I2SC_CK and I2SC_WS pins. Peripheral clock or GCLK is output as master clock on I2SC_MCK if I2SC_MR.IMCKMODE is set."]
    #[inline(always)]
    pub fn master(self) -> &'a mut crate::W<REG> {
        self.variant(MODESELECT_A::MASTER)
    }
}
#[doc = "Field `DATALENGTH` reader - Data Word Length"]
pub type DATALENGTH_R = crate::FieldReader<DATALENGTHSELECT_A>;
#[doc = "Data Word Length\n\nValue on reset: 0"]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum DATALENGTHSELECT_A {
    #[doc = "0: Data length is set to 32 bits"]
    _32_BITS = 0,
    #[doc = "1: Data length is set to 24 bits"]
    _24_BITS = 1,
    #[doc = "2: Data length is set to 20 bits"]
    _20_BITS = 2,
    #[doc = "3: Data length is set to 18 bits"]
    _18_BITS = 3,
    #[doc = "4: Data length is set to 16 bits"]
    _16_BITS = 4,
    #[doc = "5: Data length is set to 16-bit compact stereo. Left sample in bits 15:0 and right sample in bits 31:16 of same word."]
    _16_BITS_COMPACT = 5,
    #[doc = "6: Data length is set to 8 bits"]
    _8_BITS = 6,
    #[doc = "7: Data length is set to 8-bit compact stereo. Left sample in bits 7:0 and right sample in bits 15:8 of the same word."]
    _8_BITS_COMPACT = 7,
}
impl From<DATALENGTHSELECT_A> for u8 {
    #[inline(always)]
    fn from(variant: DATALENGTHSELECT_A) -> Self {
        variant as _
    }
}
impl crate::FieldSpec for DATALENGTHSELECT_A {
    type Ux = u8;
}
impl DATALENGTH_R {
    #[doc = "Get enumerated values variant"]
    #[inline(always)]
    pub fn variant(&self) -> DATALENGTHSELECT_A {
        match self.bits {
            0 => DATALENGTHSELECT_A::_32_BITS,
            1 => DATALENGTHSELECT_A::_24_BITS,
            2 => DATALENGTHSELECT_A::_20_BITS,
            3 => DATALENGTHSELECT_A::_18_BITS,
            4 => DATALENGTHSELECT_A::_16_BITS,
            5 => DATALENGTHSELECT_A::_16_BITS_COMPACT,
            6 => DATALENGTHSELECT_A::_8_BITS,
            7 => DATALENGTHSELECT_A::_8_BITS_COMPACT,
            _ => unreachable!(),
        }
    }
    #[doc = "Data length is set to 32 bits"]
    #[inline(always)]
    pub fn is_32_bits(&self) -> bool {
        *self == DATALENGTHSELECT_A::_32_BITS
    }
    #[doc = "Data length is set to 24 bits"]
    #[inline(always)]
    pub fn is_24_bits(&self) -> bool {
        *self == DATALENGTHSELECT_A::_24_BITS
    }
    #[doc = "Data length is set to 20 bits"]
    #[inline(always)]
    pub fn is_20_bits(&self) -> bool {
        *self == DATALENGTHSELECT_A::_20_BITS
    }
    #[doc = "Data length is set to 18 bits"]
    #[inline(always)]
    pub fn is_18_bits(&self) -> bool {
        *self == DATALENGTHSELECT_A::_18_BITS
    }
    #[doc = "Data length is set to 16 bits"]
    #[inline(always)]
    pub fn is_16_bits(&self) -> bool {
        *self == DATALENGTHSELECT_A::_16_BITS
    }
    #[doc = "Data length is set to 16-bit compact stereo. Left sample in bits 15:0 and right sample in bits 31:16 of same word."]
    #[inline(always)]
    pub fn is_16_bits_compact(&self) -> bool {
        *self == DATALENGTHSELECT_A::_16_BITS_COMPACT
    }
    #[doc = "Data length is set to 8 bits"]
    #[inline(always)]
    pub fn is_8_bits(&self) -> bool {
        *self == DATALENGTHSELECT_A::_8_BITS
    }
    #[doc = "Data length is set to 8-bit compact stereo. Left sample in bits 7:0 and right sample in bits 15:8 of the same word."]
    #[inline(always)]
    pub fn is_8_bits_compact(&self) -> bool {
        *self == DATALENGTHSELECT_A::_8_BITS_COMPACT
    }
}
#[doc = "Field `DATALENGTH` writer - Data Word Length"]
pub type DATALENGTH_W<'a, REG, const O: u8> =
    crate::FieldWriterSafe<'a, REG, 3, O, DATALENGTHSELECT_A>;
impl<'a, REG, const O: u8> DATALENGTH_W<'a, REG, O>
where
    REG: crate::Writable + crate::RegisterSpec,
    REG::Ux: From<u8>,
{
    #[doc = "Data length is set to 32 bits"]
    #[inline(always)]
    pub fn _32_bits(self) -> &'a mut crate::W<REG> {
        self.variant(DATALENGTHSELECT_A::_32_BITS)
    }
    #[doc = "Data length is set to 24 bits"]
    #[inline(always)]
    pub fn _24_bits(self) -> &'a mut crate::W<REG> {
        self.variant(DATALENGTHSELECT_A::_24_BITS)
    }
    #[doc = "Data length is set to 20 bits"]
    #[inline(always)]
    pub fn _20_bits(self) -> &'a mut crate::W<REG> {
        self.variant(DATALENGTHSELECT_A::_20_BITS)
    }
    #[doc = "Data length is set to 18 bits"]
    #[inline(always)]
    pub fn _18_bits(self) -> &'a mut crate::W<REG> {
        self.variant(DATALENGTHSELECT_A::_18_BITS)
    }
    #[doc = "Data length is set to 16 bits"]
    #[inline(always)]
    pub fn _16_bits(self) -> &'a mut crate::W<REG> {
        self.variant(DATALENGTHSELECT_A::_16_BITS)
    }
    #[doc = "Data length is set to 16-bit compact stereo. Left sample in bits 15:0 and right sample in bits 31:16 of same word."]
    #[inline(always)]
    pub fn _16_bits_compact(self) -> &'a mut crate::W<REG> {
        self.variant(DATALENGTHSELECT_A::_16_BITS_COMPACT)
    }
    #[doc = "Data length is set to 8 bits"]
    #[inline(always)]
    pub fn _8_bits(self) -> &'a mut crate::W<REG> {
        self.variant(DATALENGTHSELECT_A::_8_BITS)
    }
    #[doc = "Data length is set to 8-bit compact stereo. Left sample in bits 7:0 and right sample in bits 15:8 of the same word."]
    #[inline(always)]
    pub fn _8_bits_compact(self) -> &'a mut crate::W<REG> {
        self.variant(DATALENGTHSELECT_A::_8_BITS_COMPACT)
    }
}
#[doc = "Field `RXMONO` reader - Receive Mono"]
pub type RXMONO_R = crate::BitReader;
#[doc = "Field `RXMONO` writer - Receive Mono"]
pub type RXMONO_W<'a, REG, const O: u8> = crate::BitWriter<'a, REG, O>;
#[doc = "Field `RXDMA` reader - Single or Multiple DMA Controller Channels for Receiver"]
pub type RXDMA_R = crate::BitReader;
#[doc = "Field `RXDMA` writer - Single or Multiple DMA Controller Channels for Receiver"]
pub type RXDMA_W<'a, REG, const O: u8> = crate::BitWriter<'a, REG, O>;
#[doc = "Field `RXLOOP` reader - Loopback Test Mode"]
pub type RXLOOP_R = crate::BitReader;
#[doc = "Field `RXLOOP` writer - Loopback Test Mode"]
pub type RXLOOP_W<'a, REG, const O: u8> = crate::BitWriter<'a, REG, O>;
#[doc = "Field `TXMONO` reader - Transmit Mono"]
pub type TXMONO_R = crate::BitReader;
#[doc = "Field `TXMONO` writer - Transmit Mono"]
pub type TXMONO_W<'a, REG, const O: u8> = crate::BitWriter<'a, REG, O>;
#[doc = "Field `TXDMA` reader - Single or Multiple DMA Controller Channels for Transmitter"]
pub type TXDMA_R = crate::BitReader;
#[doc = "Field `TXDMA` writer - Single or Multiple DMA Controller Channels for Transmitter"]
pub type TXDMA_W<'a, REG, const O: u8> = crate::BitWriter<'a, REG, O>;
#[doc = "Field `TXSAME` reader - Transmit Data when Underrun"]
pub type TXSAME_R = crate::BitReader;
#[doc = "Field `TXSAME` writer - Transmit Data when Underrun"]
pub type TXSAME_W<'a, REG, const O: u8> = crate::BitWriter<'a, REG, O>;
#[doc = "Field `IMCKDIV` reader - Selected Clock to I2SC Master Clock Ratio"]
pub type IMCKDIV_R = crate::FieldReader;
#[doc = "Field `IMCKDIV` writer - Selected Clock to I2SC Master Clock Ratio"]
pub type IMCKDIV_W<'a, REG, const O: u8> = crate::FieldWriter<'a, REG, 6, O>;
#[doc = "Field `IMCKFS` reader - Master Clock to fs Ratio"]
pub type IMCKFS_R = crate::FieldReader<IMCKFSSELECT_A>;
#[doc = "Master Clock to fs Ratio\n\nValue on reset: 0"]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum IMCKFSSELECT_A {
    #[doc = "0: Sample frequency ratio set to 32"]
    M2SF32 = 0,
    #[doc = "1: Sample frequency ratio set to 64"]
    M2SF64 = 1,
    #[doc = "2: Sample frequency ratio set to 96"]
    M2SF96 = 2,
    #[doc = "3: Sample frequency ratio set to 128"]
    M2SF128 = 3,
    #[doc = "5: Sample frequency ratio set to 192"]
    M2SF192 = 5,
    #[doc = "7: Sample frequency ratio set to 256"]
    M2SF256 = 7,
    #[doc = "11: Sample frequency ratio set to 384"]
    M2SF384 = 11,
    #[doc = "15: Sample frequency ratio set to 512"]
    M2SF512 = 15,
    #[doc = "23: Sample frequency ratio set to 768"]
    M2SF768 = 23,
    #[doc = "31: Sample frequency ratio set to 1024"]
    M2SF1024 = 31,
    #[doc = "47: Sample frequency ratio set to 1536"]
    M2SF1536 = 47,
    #[doc = "63: Sample frequency ratio set to 2048"]
    M2SF2048 = 63,
}
impl From<IMCKFSSELECT_A> for u8 {
    #[inline(always)]
    fn from(variant: IMCKFSSELECT_A) -> Self {
        variant as _
    }
}
impl crate::FieldSpec for IMCKFSSELECT_A {
    type Ux = u8;
}
impl IMCKFS_R {
    #[doc = "Get enumerated values variant"]
    #[inline(always)]
    pub fn variant(&self) -> Option<IMCKFSSELECT_A> {
        match self.bits {
            0 => Some(IMCKFSSELECT_A::M2SF32),
            1 => Some(IMCKFSSELECT_A::M2SF64),
            2 => Some(IMCKFSSELECT_A::M2SF96),
            3 => Some(IMCKFSSELECT_A::M2SF128),
            5 => Some(IMCKFSSELECT_A::M2SF192),
            7 => Some(IMCKFSSELECT_A::M2SF256),
            11 => Some(IMCKFSSELECT_A::M2SF384),
            15 => Some(IMCKFSSELECT_A::M2SF512),
            23 => Some(IMCKFSSELECT_A::M2SF768),
            31 => Some(IMCKFSSELECT_A::M2SF1024),
            47 => Some(IMCKFSSELECT_A::M2SF1536),
            63 => Some(IMCKFSSELECT_A::M2SF2048),
            _ => None,
        }
    }
    #[doc = "Sample frequency ratio set to 32"]
    #[inline(always)]
    pub fn is_m2sf32(&self) -> bool {
        *self == IMCKFSSELECT_A::M2SF32
    }
    #[doc = "Sample frequency ratio set to 64"]
    #[inline(always)]
    pub fn is_m2sf64(&self) -> bool {
        *self == IMCKFSSELECT_A::M2SF64
    }
    #[doc = "Sample frequency ratio set to 96"]
    #[inline(always)]
    pub fn is_m2sf96(&self) -> bool {
        *self == IMCKFSSELECT_A::M2SF96
    }
    #[doc = "Sample frequency ratio set to 128"]
    #[inline(always)]
    pub fn is_m2sf128(&self) -> bool {
        *self == IMCKFSSELECT_A::M2SF128
    }
    #[doc = "Sample frequency ratio set to 192"]
    #[inline(always)]
    pub fn is_m2sf192(&self) -> bool {
        *self == IMCKFSSELECT_A::M2SF192
    }
    #[doc = "Sample frequency ratio set to 256"]
    #[inline(always)]
    pub fn is_m2sf256(&self) -> bool {
        *self == IMCKFSSELECT_A::M2SF256
    }
    #[doc = "Sample frequency ratio set to 384"]
    #[inline(always)]
    pub fn is_m2sf384(&self) -> bool {
        *self == IMCKFSSELECT_A::M2SF384
    }
    #[doc = "Sample frequency ratio set to 512"]
    #[inline(always)]
    pub fn is_m2sf512(&self) -> bool {
        *self == IMCKFSSELECT_A::M2SF512
    }
    #[doc = "Sample frequency ratio set to 768"]
    #[inline(always)]
    pub fn is_m2sf768(&self) -> bool {
        *self == IMCKFSSELECT_A::M2SF768
    }
    #[doc = "Sample frequency ratio set to 1024"]
    #[inline(always)]
    pub fn is_m2sf1024(&self) -> bool {
        *self == IMCKFSSELECT_A::M2SF1024
    }
    #[doc = "Sample frequency ratio set to 1536"]
    #[inline(always)]
    pub fn is_m2sf1536(&self) -> bool {
        *self == IMCKFSSELECT_A::M2SF1536
    }
    #[doc = "Sample frequency ratio set to 2048"]
    #[inline(always)]
    pub fn is_m2sf2048(&self) -> bool {
        *self == IMCKFSSELECT_A::M2SF2048
    }
}
#[doc = "Field `IMCKFS` writer - Master Clock to fs Ratio"]
pub type IMCKFS_W<'a, REG, const O: u8> = crate::FieldWriter<'a, REG, 6, O, IMCKFSSELECT_A>;
impl<'a, REG, const O: u8> IMCKFS_W<'a, REG, O>
where
    REG: crate::Writable + crate::RegisterSpec,
    REG::Ux: From<u8>,
{
    #[doc = "Sample frequency ratio set to 32"]
    #[inline(always)]
    pub fn m2sf32(self) -> &'a mut crate::W<REG> {
        self.variant(IMCKFSSELECT_A::M2SF32)
    }
    #[doc = "Sample frequency ratio set to 64"]
    #[inline(always)]
    pub fn m2sf64(self) -> &'a mut crate::W<REG> {
        self.variant(IMCKFSSELECT_A::M2SF64)
    }
    #[doc = "Sample frequency ratio set to 96"]
    #[inline(always)]
    pub fn m2sf96(self) -> &'a mut crate::W<REG> {
        self.variant(IMCKFSSELECT_A::M2SF96)
    }
    #[doc = "Sample frequency ratio set to 128"]
    #[inline(always)]
    pub fn m2sf128(self) -> &'a mut crate::W<REG> {
        self.variant(IMCKFSSELECT_A::M2SF128)
    }
    #[doc = "Sample frequency ratio set to 192"]
    #[inline(always)]
    pub fn m2sf192(self) -> &'a mut crate::W<REG> {
        self.variant(IMCKFSSELECT_A::M2SF192)
    }
    #[doc = "Sample frequency ratio set to 256"]
    #[inline(always)]
    pub fn m2sf256(self) -> &'a mut crate::W<REG> {
        self.variant(IMCKFSSELECT_A::M2SF256)
    }
    #[doc = "Sample frequency ratio set to 384"]
    #[inline(always)]
    pub fn m2sf384(self) -> &'a mut crate::W<REG> {
        self.variant(IMCKFSSELECT_A::M2SF384)
    }
    #[doc = "Sample frequency ratio set to 512"]
    #[inline(always)]
    pub fn m2sf512(self) -> &'a mut crate::W<REG> {
        self.variant(IMCKFSSELECT_A::M2SF512)
    }
    #[doc = "Sample frequency ratio set to 768"]
    #[inline(always)]
    pub fn m2sf768(self) -> &'a mut crate::W<REG> {
        self.variant(IMCKFSSELECT_A::M2SF768)
    }
    #[doc = "Sample frequency ratio set to 1024"]
    #[inline(always)]
    pub fn m2sf1024(self) -> &'a mut crate::W<REG> {
        self.variant(IMCKFSSELECT_A::M2SF1024)
    }
    #[doc = "Sample frequency ratio set to 1536"]
    #[inline(always)]
    pub fn m2sf1536(self) -> &'a mut crate::W<REG> {
        self.variant(IMCKFSSELECT_A::M2SF1536)
    }
    #[doc = "Sample frequency ratio set to 2048"]
    #[inline(always)]
    pub fn m2sf2048(self) -> &'a mut crate::W<REG> {
        self.variant(IMCKFSSELECT_A::M2SF2048)
    }
}
#[doc = "Field `IMCKMODE` reader - Master Clock Mode"]
pub type IMCKMODE_R = crate::BitReader;
#[doc = "Field `IMCKMODE` writer - Master Clock Mode"]
pub type IMCKMODE_W<'a, REG, const O: u8> = crate::BitWriter<'a, REG, O>;
#[doc = "Field `IWS` reader - I2SC_WS Slot Width"]
pub type IWS_R = crate::BitReader;
#[doc = "Field `IWS` writer - I2SC_WS Slot Width"]
pub type IWS_W<'a, REG, const O: u8> = crate::BitWriter<'a, REG, O>;
impl R {
    #[doc = "Bit 0 - Inter-IC Sound Controller Mode"]
    #[inline(always)]
    pub fn mode(&self) -> MODE_R {
        MODE_R::new((self.bits & 1) != 0)
    }
    #[doc = "Bits 2:4 - Data Word Length"]
    #[inline(always)]
    pub fn datalength(&self) -> DATALENGTH_R {
        DATALENGTH_R::new(((self.bits >> 2) & 7) as u8)
    }
    #[doc = "Bit 8 - Receive Mono"]
    #[inline(always)]
    pub fn rxmono(&self) -> RXMONO_R {
        RXMONO_R::new(((self.bits >> 8) & 1) != 0)
    }
    #[doc = "Bit 9 - Single or Multiple DMA Controller Channels for Receiver"]
    #[inline(always)]
    pub fn rxdma(&self) -> RXDMA_R {
        RXDMA_R::new(((self.bits >> 9) & 1) != 0)
    }
    #[doc = "Bit 10 - Loopback Test Mode"]
    #[inline(always)]
    pub fn rxloop(&self) -> RXLOOP_R {
        RXLOOP_R::new(((self.bits >> 10) & 1) != 0)
    }
    #[doc = "Bit 12 - Transmit Mono"]
    #[inline(always)]
    pub fn txmono(&self) -> TXMONO_R {
        TXMONO_R::new(((self.bits >> 12) & 1) != 0)
    }
    #[doc = "Bit 13 - Single or Multiple DMA Controller Channels for Transmitter"]
    #[inline(always)]
    pub fn txdma(&self) -> TXDMA_R {
        TXDMA_R::new(((self.bits >> 13) & 1) != 0)
    }
    #[doc = "Bit 14 - Transmit Data when Underrun"]
    #[inline(always)]
    pub fn txsame(&self) -> TXSAME_R {
        TXSAME_R::new(((self.bits >> 14) & 1) != 0)
    }
    #[doc = "Bits 16:21 - Selected Clock to I2SC Master Clock Ratio"]
    #[inline(always)]
    pub fn imckdiv(&self) -> IMCKDIV_R {
        IMCKDIV_R::new(((self.bits >> 16) & 0x3f) as u8)
    }
    #[doc = "Bits 24:29 - Master Clock to fs Ratio"]
    #[inline(always)]
    pub fn imckfs(&self) -> IMCKFS_R {
        IMCKFS_R::new(((self.bits >> 24) & 0x3f) as u8)
    }
    #[doc = "Bit 30 - Master Clock Mode"]
    #[inline(always)]
    pub fn imckmode(&self) -> IMCKMODE_R {
        IMCKMODE_R::new(((self.bits >> 30) & 1) != 0)
    }
    #[doc = "Bit 31 - I2SC_WS Slot Width"]
    #[inline(always)]
    pub fn iws(&self) -> IWS_R {
        IWS_R::new(((self.bits >> 31) & 1) != 0)
    }
}
impl W {
    #[doc = "Bit 0 - Inter-IC Sound Controller Mode"]
    #[inline(always)]
    #[must_use]
    pub fn mode(&mut self) -> MODE_W<MR_SPEC, 0> {
        MODE_W::new(self)
    }
    #[doc = "Bits 2:4 - Data Word Length"]
    #[inline(always)]
    #[must_use]
    pub fn datalength(&mut self) -> DATALENGTH_W<MR_SPEC, 2> {
        DATALENGTH_W::new(self)
    }
    #[doc = "Bit 8 - Receive Mono"]
    #[inline(always)]
    #[must_use]
    pub fn rxmono(&mut self) -> RXMONO_W<MR_SPEC, 8> {
        RXMONO_W::new(self)
    }
    #[doc = "Bit 9 - Single or Multiple DMA Controller Channels for Receiver"]
    #[inline(always)]
    #[must_use]
    pub fn rxdma(&mut self) -> RXDMA_W<MR_SPEC, 9> {
        RXDMA_W::new(self)
    }
    #[doc = "Bit 10 - Loopback Test Mode"]
    #[inline(always)]
    #[must_use]
    pub fn rxloop(&mut self) -> RXLOOP_W<MR_SPEC, 10> {
        RXLOOP_W::new(self)
    }
    #[doc = "Bit 12 - Transmit Mono"]
    #[inline(always)]
    #[must_use]
    pub fn txmono(&mut self) -> TXMONO_W<MR_SPEC, 12> {
        TXMONO_W::new(self)
    }
    #[doc = "Bit 13 - Single or Multiple DMA Controller Channels for Transmitter"]
    #[inline(always)]
    #[must_use]
    pub fn txdma(&mut self) -> TXDMA_W<MR_SPEC, 13> {
        TXDMA_W::new(self)
    }
    #[doc = "Bit 14 - Transmit Data when Underrun"]
    #[inline(always)]
    #[must_use]
    pub fn txsame(&mut self) -> TXSAME_W<MR_SPEC, 14> {
        TXSAME_W::new(self)
    }
    #[doc = "Bits 16:21 - Selected Clock to I2SC Master Clock Ratio"]
    #[inline(always)]
    #[must_use]
    pub fn imckdiv(&mut self) -> IMCKDIV_W<MR_SPEC, 16> {
        IMCKDIV_W::new(self)
    }
    #[doc = "Bits 24:29 - Master Clock to fs Ratio"]
    #[inline(always)]
    #[must_use]
    pub fn imckfs(&mut self) -> IMCKFS_W<MR_SPEC, 24> {
        IMCKFS_W::new(self)
    }
    #[doc = "Bit 30 - Master Clock Mode"]
    #[inline(always)]
    #[must_use]
    pub fn imckmode(&mut self) -> IMCKMODE_W<MR_SPEC, 30> {
        IMCKMODE_W::new(self)
    }
    #[doc = "Bit 31 - I2SC_WS Slot Width"]
    #[inline(always)]
    #[must_use]
    pub fn iws(&mut self) -> IWS_W<MR_SPEC, 31> {
        IWS_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.bits = bits;
        self
    }
}
#[doc = "Mode Register\n\nYou can [`read`](crate::generic::Reg::read) this register and get [`mr::R`](R).  You can [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`write_with_zero`](crate::generic::Reg::write_with_zero) this register using [`mr::W`](W). You can also [`modify`](crate::generic::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api)."]
pub struct MR_SPEC;
impl crate::RegisterSpec for MR_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [`mr::R`](R) reader structure"]
impl crate::Readable for MR_SPEC {}
#[doc = "`write(|w| ..)` method takes [`mr::W`](W) writer structure"]
impl crate::Writable for MR_SPEC {
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets MR to value 0"]
impl crate::Resettable for MR_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
